create database Sales_Project_db;

use Sales_Project_db;

select * from Retail_Sales; 

SELECT top 10 * FROM retail_sales;

SELECT COUNT(*) as total_rows FROM retail_sales;

-- Data Cleaning
SELECT * FROM retail_sales
  WHERE 
    transaction_id IS NULL
    OR
    sales_date IS NULL
    OR 
    sales_time IS NULL
    OR
    customer_id IS NULL
    OR
    gender IS NULL
    OR
    age IS NULL
    OR
    category IS NULL
    OR
    quantity  IS NULL
    OR
    price_per_unit IS NULL
    OR
    cogs IS NULL
    OR
    total_sales IS NULL;
--
Delete FROM retail_sales
  WHERE 
    transaction_id IS NULL
    OR
    customer_id IS NULL
    OR
    quantity  IS NULL
    OR
    price_per_unit IS NULL
    OR
    cogs IS NULL
    OR
    total_sales IS NULL;

-- Data Exploration -

-- How many sales we have?
SELECT COUNT(*) as total_sales_count FROM retail_sales;

-- How many uniuque customers we have ?
SELECT COUNT(DISTINCT customer_id) as uniuque_customer FROM retail_sales;

SELECT DISTINCT category FROM retail_sales;

-- Data Analysis & Business Key Problems & Answers.

 /*  My Analysis & Findings --
Q.1 Write a SQL query to retrieve all columns for sales made on '2022-11-05.

Q.2 Write a SQL query to retrieve all transactions where the category is 
      'Clothing' and the quantity sold is more than 3 in the month of Nov-2022.

Q.3 Write a SQL query to calculate the total sales (total_sale) for each category.

Q.4 Write a SQL query to find the net profit margin percentage for each category.

Q.5 Write a SQL query to find the average age of customers who purchased items from
      the 'Beauty' category.

Q.6 Write a SQL query to find all transactions where the total_sale is greater than 1000.

Q.7 Write a SQL query to find the total number of transactions (transaction_id) made by 
      each gender in each category.

Q.8 Write a SQL query to find the total revenue generated by each gender within each category.

Q.9 Write a SQL query to calculate the average sale for each month in each year.

Q.10 Write a SQL query to find the top 5 customers based on the highest total sales 

Q.11 Write a SQL query to find the number of unique customers who purchased items
      from each category.

Q.12 Write a SQL query to find the customers who have placed more than 50 orders.

Q.13 Write a SQL query to Find the top 3 highest-valued orders within each category.  */



-- Q.1 Write a SQL query to retrieve all columns for sales made on '2022-11-05.
SELECT *
FROM retail_sales
WHERE sales_date = '2022-11-05';

--Q.2 Write a SQL query to retrieve all transactions where the category is 
--    'Clothing' and the quantity sold is more than 3 in the month of Nov-2022.
SELECT *
FROM retail_sales
WHERE category = 'Clothing'
  AND quantity >3
  AND YEAR(sales_date) = 2022 
  AND MONTH(sales_date) = 11;

--Q.3 Write a SQL query to calculate the total sales (total_sale) for each category.
SELECT 
    category,
    SUM(total_sales) as net_sale,
    COUNT(*) as total_orders
FROM retail_sales
GROUP BY category order by net_sale desc;

--Q.4 Write a SQL query to find the net profit margin percentage for each category.
SELECT 
    category,
    ROUND(SUM(total_sales - cogs) / SUM(total_sales) * 100, 2) AS profit_margin_percentage
FROM retail_sales
GROUP BY category
ORDER BY profit_margin_percentage DESC;

--Q.5 Write a SQL query to find the average age of customers who purchased items from
--    the 'Beauty' category.
SELECT
    ROUND(AVG(age), 2) as avg_age
FROM retail_sales
WHERE category = 'Beauty';

--Q.6 Write a SQL query to find all transactions where the total_sale is greater than 1000.
SELECT * FROM retail_sales
WHERE total_sales > 1000;

--Q.7 Write a SQL query to find the total number of transactions (transaction_id) made by 
--     each gender in each category.
SELECT category,gender,
    COUNT(*) as total_trans
FROM retail_sales
GROUP BY 
    category,gender ORDER BY category;

--Q.8 Write a SQL query to find the total revenue generated by each gender within each category.
SELECT 
    category,
    gender,
    SUM(total_sales) AS total_revenue
FROM retail_sales
GROUP BY category, gender
ORDER BY category, total_revenue DESC;

--Q.9 Write a SQL query to calculate the average sale for each month in each year. 
SELECT
    YEAR(sales_date) AS year,
    MONTH(sales_date) AS month,
    ROUND(AVG(total_sales), 2) AS avg_sales
FROM retail_sales 
GROUP BY YEAR(sales_date), MONTH(sales_date) 
ORDER BY avg_sales desc;

  --Q.10 Write a SQL query to find the top 5 customers based on the highest total sales 
WITH CustomerSales AS
(SELECT customer_id, 
    SUM(total_sales) AS grand_total_sales,
    DENSE_RANK() OVER (ORDER BY SUM(total_sales) DESC) AS ranka
    FROM retail_sales
    GROUP BY customer_id)
    SELECT * FROM CustomerSales WHERE ranka <= 5;

 --Q.11 Write a SQL query to find the number of unique customers who purchased items
 --    from each category.
 SELECT 
    category,
    COUNT(DISTINCT customer_id) AS unique_customers_count
FROM retail_sales GROUP BY category
ORDER BY unique_customers_count DESC;

--Q.12 Write a SQL query to find the customers who have placed more than 50 orders.
SELECT 
    customer_id,
    COUNT(transaction_id) AS total_orders
FROM retail_sales
GROUP BY customer_id
HAVING COUNT(transaction_id) > 50
ORDER BY total_orders DESC;

--Q.13 Write a SQL query to Find the top 3 highest-valued orders within each category.
WITH RankedProducts AS
    (SELECT 
       category,customer_id,total_sales,
        dense_rank() OVER (PARTITION BY category ORDER BY total_sales DESC) AS rank_num
    FROM retail_sales)
SELECT * FROM RankedProducts
WHERE rank_num <= 3;



